---
title: "git_00"
author: "Jeremy Baker"
date: "Year 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Five little girls of Five, Four, Three, Two, One:  
Rolling on the hearthrug, full of tricks and fun.  
Five rosy girls, in years from Ten to Six:  
Sitting down to lessons--no more time for tricks.  
  
Five growing girls, from Fifteen to Eleven:  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Something there is that doesn't love a wall,  
That sends the frozen-ground-swell under it,  
And spills the upper boulders in the sun;  
And makes gaps even two can pass abreast.  
The work of hunters is another thing:  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
  
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Once upon a midnight dreary, while I pondered, weak and weary,  
Over many a quaint and curious volume of forgotten lore—  
    While I nodded, nearly napping, suddenly there came a tapping,  
As of some one gently rapping, rapping at my chamber door.  
“’Tis some visitor,” I muttered, “tapping at my chamber door—  
            Only this and nothing more.”  
  
  Once upon a midnight dreary, while I pondered, weak and weary,
Over many a quaint and curious volume of forgotten lore—
    While I nodded, nearly napping, suddenly there came a tapping,
As of some one gently rapping, rapping at my chamber door.
“’Tis some visitor,” I muttered, “tapping at my chamber door—
            Only this and nothing more.”

  Ah, distinctly I remember it was in the bleak December;  
And each separate dying ember wrought its ghost upon the floor.
    Eagerly I wished the morrow;—vainly I had sought to borrow
    From my books surcease of sorrow—sorrow for the lost Lenore—
For the rare and radiant maiden whom the angels name Lenore—
            Nameless here for evermore.

And each separate dying ember wrought its ghost upon the floor.  
    Eagerly I wished the morrow;—vainly I had sought to borrow  
    From my books surcease of sorrow—sorrow for the lost Lenore—  
For the rare and radiant maiden whom the angels name Lenore—  
            Nameless here for evermore.  
  
  
